name: github action demo

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      - name: echo
        run: echo "hello world"
      