name: github action demo

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello world"
        
  build-deploy:
    runs-on: ubuntu-latest
    needs: echo
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: npm i && npm run export
      
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: /
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN }}
          output_location: "out"
          
          repo_token: ${{ secrets.GITHUB_TOKEN }}
